# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];

    fileSystems."/" = {
            device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
            fsType = "ext4";
    };

    fileSystems."/nix" = {
        device = "/dev/disk/by-uuid/f527024c-4158-4479-b96e-885fc6e63713";
        fsType = "ext4";
    };

    fileSystems."/data" = {
        device = "/dev/disk/by-uuid/1fc6d92d-8f9d-4bad-9dfd-c14dbb1021c2";
        fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c157f7eb-15df-400d-b419-1d1267bf3626"; }
    ];
}
